"""init business tables

Revision ID: 26321e0bb705
Revises: 
Create Date: 2026-07-09 22:58:56.397968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '26321e0bb705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('task_id', sa.UUID(), nullable=True, comment='关联任务，冒烟测试等场景可为空'),
    sa.Column('node', sa.String(length=100), nullable=False, comment='调用来源节点名，如 content_writer'),
    sa.Column('call_type', sa.String(length=20), nullable=False, comment='text / image'),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='完整输入（system + user 等）'),
    sa.Column('response', sa.Text(), nullable=True, comment='完整响应文本或图片路径'),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_task_id'), 'llm_call_logs', ['task_id'], unique=False)
    op.create_table('tasks',
    sa.Column('direction', sa.String(length=500), nullable=False, comment='用户输入的内容方向'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='running / completed / cancelled / failed'),
    sa.Column('current_stage', sa.String(length=50), nullable=False, comment='当前阶段，供前端展示'),
    sa.Column('thread_id', sa.String(length=100), nullable=False, comment='LangGraph checkpoint 线程 ID'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('content_versions',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号，从 1 开始'),
    sa.Column('content', sa.Text(), nullable=False, comment='文案内容'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='人工对该版本的修改意见（通过则为空）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft / rejected / approved'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_task_id'), 'content_versions', ['task_id'], unique=False)
    op.create_table('images',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='序号（第几张）'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='该图承载的文案摘要'),
    sa.Column('gen_prompt', sa.Text(), nullable=False, comment='生成图片使用的 Prompt'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='本地文件相对路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='generated / rejected / approved'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重绘次数'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_task_id'), 'images', ['task_id'], unique=False)
    op.create_table('publish_records',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False, comment='平台标识，如 xiaohongshu'),
    sa.Column('content_package', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='平台适配后的内容包'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending / published'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='人工标记已发布的时间'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_records_task_id'), 'publish_records', ['task_id'], unique=False)
    op.create_table('topics',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='选题标题'),
    sa.Column('angle', sa.Text(), nullable=False, comment='切入角度'),
    sa.Column('target_audience', sa.String(length=200), nullable=False, comment='目标人群'),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False, comment='生成批次（重新生成时递增）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_task_id'), 'topics', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_task_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_publish_records_task_id'), table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_index(op.f('ix_images_task_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_content_versions_task_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_llm_call_logs_task_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
